default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: lolbox_srv_development

test:
  <<: *default
  database: lolbox_srv_test

production:
  <<: *default
  database: <%= ENV['MYSQL_NAME'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
