development:
  clients:
    default:
      database: lolcaf_development
      hosts:
        - localhost:27017
      options:
        max_pool_size: 100
  options:
test:
  clients:
    default:
      database: lolcaf_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 100
production:
  clients:
    default:
      database: <%= ENV['MONGODB_NAME'] || 'lolcaf_production' %>
      hosts:
        - <%= ENV['MONGODB_URI'] %>
      <% if ENV['MONGODB_USERNAME'].present? %>
      user: <%= ENV['MONGODB_USERNAME'] %>
      password: <%= ENV['MONGODB_PASSWORD'] %>
      <% end %>
      options:
        max_pool_size: 100