# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a799ae93db1df84054754a4e6fe4b92348d38f575c2f1a398c33f8c528bee7efa6615ee9e3022362ab244121a30c0565a5daf767c3aa5d6ab0d7b876aa9a745

test:
  secret_key_base: cfd6104e1ff682050f78194e071d16bf30bb75188369743e8505e2a1ccd7806b392c67914aa86421842f1b949e53f4fd1cd7ef9c11551ad58c73d84bab8a6037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
